# Generated by Django 2.0.10 on 2019-01-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190114_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='_points',
            field=models.IntegerField(db_column='points', default=0),
        ),
    ]
