# Generated by Django 2.0 on 2017-12-07 21:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AddField(
            model_name='page',
            name='file',
            field=models.FileField(null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/home/odinj/Desktop/git/yactff/web/pages/web/')),
        ),
    ]
