# Generated by Django 2.0 on 2019-01-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190114_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='_points',
        ),
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
