# Generated by Django 2.0 on 2017-12-10 18:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171207_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/mnt/raid1/data/git/yactff/web/pages/web/'), upload_to=''),
        ),
    ]
