# Generated by Django 2.0 on 2017-12-11 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171210_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, upload_to='team/logo/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='solved_challenges',
            field=models.ManyToManyField(null=True, through='web.SolvedChallenge', to='web.Challenge'),
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
