# Generated by Django 2.0 on 2017-12-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171211_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='solved_challenges',
            field=models.ManyToManyField(through='web.SolvedChallenge', to='web.Challenge'),
        ),
    ]
